version: '3.5'

services:
  api:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: api-container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    network_mode: bridge
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-container
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    network_mode: bridge

volumes:
  redis-data: